package schema

import (
	"strings"
	"time"
	"unicode"
	"unicode/utf8"
)

// FileRef identifies the file a finding points at.
//
// SHA256 is mandatory: it is the deduplication key across engines. The same
// file flagged by N engines = N votes on the same target.
type FileRef struct {
	Path      string    `json:"path"`
	SizeBytes int64     `json:"size_bytes"`
	SHA256    string    `json:"sha256"`
	MD5       string    `json:"md5,omitempty"`
	MTime     time.Time `json:"mtime"`
	Owner     string    `json:"owner,omitempty"`
	// Perms is the octal permission as a string ("0644"), preserved so that
	// restoring from quarantine puts the file back exactly as it was.
	Perms string `json:"perms,omitempty"`
	// Location says whether the web serves this file: web_reachable, trash,
	// outside_docroot, or unknown.
	//
	// It is context for a human deciding what to look at first, and an input to the
	// ACTION — never to the score. A webshell in the document root can be run by anyone
	// with the URL this minute; the same webshell in the trash cannot be run by anybody,
	// and is still a webshell, still reported at its real level.
	Location string `json:"location,omitempty"`
}

// Component describes the vulnerable component of a kind=vulnerability finding.
//
// Defined in docs/schema-and-adapters.md section 3.1. The MVP does not produce
// these findings — the type exists so that feature 002 does not require
// breaking the schema (DECISIONS.md D-013).
type Component struct {
	// Type: "wordpress-plugin", "wordpress-theme", "wordpress-core",
	// "composer-package", "npm-package".
	Type             string   `json:"type"`
	Slug             string   `json:"slug"`
	InstalledVersion string   `json:"installed_version"`
	FixedIn          string   `json:"fixed_in,omitempty"`
	VulnIDs          []string `json:"vuln_ids,omitempty"`
	CVSS             float64  `json:"cvss,omitempty"`
	ExploitedInWild  bool     `json:"exploited_in_wild,omitempty"`
}

// Finding is one individual finding reported by one engine, already normalized.
//
// A Finding is always ONE engine's opinion about ONE file. Consolidation across
// engines happens in the Verdict, never here.
type Finding struct {
	SchemaVersion string `json:"schema_version"`
	// ID is generated by the orchestrator, never by the adapter.
	ID string `json:"id"`
	// Kind discriminates malware/vulnerability/hardening. Empty is treated as
	// KindMalware during normalization, for compatibility with adapters written
	// before section 3 of the schema existed.
	Kind          Kind   `json:"kind,omitempty"`
	Engine        string `json:"engine"`
	EngineVersion string `json:"engine_version,omitempty"`
	// Rule is the name of the signature/rule that matched, as the engine
	// reports it.
	Rule    string `json:"rule"`
	RuleRef string `json:"rule_ref,omitempty"`

	File FileRef `json:"file"`

	Category   Category   `json:"category"`
	Severity   Severity   `json:"severity"`
	Confidence Confidence `json:"confidence"`

	// MatchedContent is the snippet that triggered the rule: truncated to
	// MaxMatchedContentBytes and sanitized. Never executable.
	MatchedContent string `json:"matched_content,omitempty"`
	MatchedOffset  int64  `json:"matched_offset,omitempty"`

	// Component is only filled when Kind == KindVulnerability.
	Component *Component `json:"component,omitempty"`

	ScanID     string    `json:"scan_id"`
	DetectedAt time.Time `json:"detected_at"`
}

// EffectiveKind returns the Kind, treating empty as malware.
func (f Finding) EffectiveKind() Kind {
	if f.Kind == "" {
		return KindMalware
	}
	return f.Kind
}

// SanitizeSnippet prepares a snippet of a suspicious file to be carried in the
// schema and displayed in the UI.
//
// The constitution forbids re-serving malicious content. Here that means:
// truncate at MaxMatchedContentBytes (respecting rune boundaries), strip
// control bytes that could break a terminal or a log, and replace invalid UTF-8
// sequences with a marker. The function does NOT try to defang the payload —
// that is the job of whoever renders it (HTML escaping) and of the fact that
// the snippet is never handed to an interpreter.
func SanitizeSnippet(raw string) string {
	if len(raw) > MaxMatchedContentBytes {
		raw = raw[:MaxMatchedContentBytes]
		// Don't cut a rune in half.
		for len(raw) > 0 && !utf8.ValidString(raw) {
			raw = raw[:len(raw)-1]
		}
	}

	var b strings.Builder
	b.Grow(len(raw))
	for _, r := range raw {
		switch {
		case r == utf8.RuneError:
			b.WriteByte('.')
		case r == '\n' || r == '\r' || r == '\t':
			b.WriteByte(' ')
		case unicode.IsControl(r):
			b.WriteByte('.')
		default:
			b.WriteRune(r)
		}
	}
	return strings.TrimSpace(b.String())
}
